// tailwind.config.js
module.exports = {
  prefix: '',
  mode: 'jit',
  important: false,
  content: ["./src/**/*.{html,ts}",],
  darkMode: 'class',
  theme: {
    extend: {
      keyframes: {
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        'fade-in-down': {
          '0%': {
            opacity: '0',
            transform: 'translateY(-10px)',
          },
          '100%': {
            opacity: '1',
            transform: 'translateY(0)',
          },
        },
        'fade-out-down': {
          from: {
            opacity: '1',
            transform: 'translateY(0px)',
          },
          to: {
            opacity: '0',
            transform: 'translateY(10px)',
          },
        },
        'fade-in-up': {
          '0%': {
            opacity: '0',
            transform: 'translateY(10px)',
          },
          '100%': {
            opacity: '1',
            transform: 'translateY(0)',
          },
        },
        'fade-out-up': {
          from: {
            opacity: '1',
            transform: 'translateY(0px)',
          },
          to: {
            opacity: '0',
            transform: 'translateY(10px)',
          },
        },
      },
      animation: {
        wiggle: 'wiggle 1s ease-in-out infinite',
        'fade-in-down': 'fade-in-down 0.3s ease-out',
        'fade-out-down': 'fade-out-down 0.3s ease-out',
        'fade-in-up': 'fade-in-up 0.3s ease-out',
        'fade-out-up': 'fade-out-up 0.3s ease-out',
      },
      colors: {
        // Custom colors from your design system
        'background': 'var(--sys-background)',
        'on-background': 'var(--sys-on-background)',
        'surface': 'var(--sys-surface)',
        'surface-dim': 'var(--sys-surface-dim)',
        'surface-bright': 'var(--sys-surface-bright)',
        'surface-container-lowest': 'var(--sys-surface-container-lowest)',
        'surface-container-low': 'var(--sys-surface-container-low)',
        'surface-container': 'var(--sys-surface-container)',
        'surface-container-high': 'var(--sys-surface-container-high)',
        'surface-container-highest': 'var(--sys-surface-container-highest)',
        'on-surface': 'var(--sys-on-surface)',
        'surface-variant': 'var(--sys-surface-variant)',
        'on-surface-variant': 'var(--sys-on-surface-variant)',
        'inverse-surface': 'var(--sys-inverse-surface)',
        'inverse-on-surface': 'var(--sys-inverse-on-surface)',
        'outline': 'var(--sys-outline)',
        'outline-variant': 'var(--sys-outline-variant)',
        'shadow': 'var(--sys-shadow)',
        'scrim': 'var(--sys-scrim)',
        'surface-tint': 'var(--sys-surface-tint)',
        'primary': 'var(--sys-primary)',
        'on-primary': 'var(--sys-on-primary)',
        'primary-container': 'var(--sys-primary-container)',
        'on-primary-container': 'var(--sys-on-primary-container)',
        'inverse-primary': 'var(--sys-inverse-primary)',
        'secondary': 'var(--sys-secondary)',
        'on-secondary': 'var(--sys-on-secondary)',
        'secondary-container': 'var(--sys-secondary-container)',
        'on-secondary-container': 'var(--sys-on-secondary-container)',
        'tertiary': 'var(--sys-tertiary)',
        'on-tertiary': 'var(--sys-on-tertiary)',
        'tertiary-container': 'var(--sys-tertiary-container)',
        'on-tertiary-container': 'var(--sys-on-tertiary-container)',
        'error': 'var(--sys-error)',
        'on-error': 'var(--sys-on-error)',
        'error-container': 'var(--sys-error-container)',
        'on-error-container': 'var(--sys-on-error-container)',
        'neutral': 'var(--sys-neutral)',
        'neutral-variant': 'var(--sys-neutral-variant)',
        'primary-fixed': 'var(--sys-primary-fixed)',
        'primary-fixed-dim': 'var(--sys-primary-fixed-dim)',
        'on-primary-fixed': 'var(--sys-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--sys-on-primary-fixed-variant)',
        'secondary-fixed': 'var(--sys-secondary-fixed)',
        'secondary-fixed-dim': 'var(--sys-secondary-fixed-dim)',
        'on-secondary-fixed': 'var(--sys-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--sys-on-secondary-fixed-variant)',
        'tertiary-fixed': 'var(--sys-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--sys-tertiary-fixed-dim)',
        'on-tertiary-fixed': 'var(--sys-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--sys-on-tertiary-fixed-variant)',
        'inverse-secondary': 'var(--sys-inverse-secondary)',
        'inverse-tertiary': 'var(--sys-inverse-tertiary)',
        'inverse-error': 'var(--sys-inverse-error)',
        'error-fixed': 'var(--sys-error-fixed)',
        'error-fixed-dim': 'var(--sys-error-fixed-dim)',
        'on-error-fixed': 'var(--sys-on-error-fixed)',
        'on-error-fixed-variant': 'var(--sys-on-error-fixed-variant)',
      },
      fontSize: {
        'display-large': ['2rem', { lineHeight: '2.5rem' }],
        'display-medium': ['1.75rem', { lineHeight: '2.25rem' }],
        'display-small': ['1.5rem', { lineHeight: '2rem' }],
        'headline-large': ['1.375rem', { lineHeight: '1.75rem' }],
        'headline-medium': ['1.25rem', { lineHeight: '1.5rem' }],
        'headline-small': ['1.125rem', { lineHeight: '1.5rem' }],
        'title-large': ['1.125rem', { lineHeight: '1.5rem' }],
        'title-medium': ['1rem', { lineHeight: '1.5rem' }],
        'title-small': ['0.875rem', { lineHeight: '1.25rem' }],
        'label-large': ['1rem', { lineHeight: '1.5rem' }],
        'label-medium': ['0.875rem', { lineHeight: '1.25rem' }],
        'label-small': ['0.75rem', { lineHeight: '1rem' }],
        'body-large': ['1rem', { lineHeight: '1.5rem' }],
        'body-medium': ['0.875rem', { lineHeight: '1.25rem' }],
        'body-small': ['0.75rem', { lineHeight: '1rem' }],
      },
    },
  },
  plugins: [],
}
